tasks:
  set_extended_memory_limit: true
  notarize: false
  clean: true

build:
  win: true
  mac: true
  android: true

renutil:
  version: "latest"
  registry: "cache"

renotize:
  apple_id: fill-this-in
  password: fill-this-in
  identity: fill-this-in
  bundle: com.my-organization.my-game
  altool_extra:
